# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 肯尼的程式分享Blog
email: d8956303@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  這裡是肯尼的程式分享Blog<br/>
  記錄著我在工作上遇到的程式開發問題及心得分享
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kenychen.com" # the base hostname & protocol for your site
twitter_username: kenychen
github_username:  kenychen

# Build settings
markdown: kramdown
highlighter: rouge
